{
 "title": "GeoKrety Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Rate Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geokrety_rate_limit", "legendFormat": "{{type}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "geokrety_total_requests", "legendFormat": "{{verb}}" },
    { "expr": "sum(geokrety_accounts_total)", "legendFormat": "Accounts" },
    { "expr": "sum(geokrety_geokrety_total)", "legendFormat": "GeoKrety" },
    { "expr": "geokrety_sessions_total", "legendFormat": "sessions {{status}}" }
   ]
  },
  {
   "title": "GK version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geokrety_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Accounts status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geokrety_accounts_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "GeoKrety Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geokrety_geokrety_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Locked scripts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(geokrety_scripts{status=\"unlocks\"}[30s]))",
     "legendFormat": "unlocks"
    },
    {
     "expr": "ceil(rate(geokrety_scripts{status=\"acks\"}[30s]))",
     "legendFormat": "acks"
    },
    {
     "expr": "geokrety_scripts{status=\"locks\"}",
     "legendFormat": "locks"
    }
   ]
  },
  {
   "title": "Moves Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geokrety_moves_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Pictures types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geokrety_pictures_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Waypoint update status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 18 },
   "targets": [
    { "expr": "geokrety_waypoint_sync_status", "legendFormat": "{{provider}}" }
   ]
  },
  {
   "title": "Login",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geokrety_explicit_logout_total", "legendFormat": "Logout" },
    { "expr": "geokrety_logged_in_users_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Mail sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Mail sent" }
   ],
   "targets": [
    { "expr": "geokrety_mail", "legendFormat": "Mails sent" }
   ]
  },
  {
   "title": "Daily mail stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    { "expr": "geokrety_cron_dailymail", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "geokrety_moves_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(geokrety_moves_total)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connected users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geokrety_sessions_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Waypoints statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "geokrety_waypoints_total", "legendFormat": "{{provider}}" }
   ]
  },
  {
   "title": "OKAPI PL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"added\",provider=\"OC_PL\"}",
     "legendFormat": "Added"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"updated\",provider=\"OC_PL\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"skipped\",provider=\"OC_PL\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"deleted\",provider=\"OC_PL\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"error\",provider=\"OC_PL\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "OKAPI NL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"added\",provider=\"OC_NL\"}",
     "legendFormat": "Added"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"updated\",provider=\"OC_NL\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"skipped\",provider=\"OC_NL\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"deleted\",provider=\"OC_NL\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"error\",provider=\"OC_NL\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "OKAPI DE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"added\",provider=\"OC_DE\"}",
     "legendFormat": "Added"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"updated\",provider=\"OC_DE\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"skipped\",provider=\"OC_DE\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"deleted\",provider=\"OC_DE\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"error\",provider=\"OC_DE\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "OKAPI RO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"added\",provider=\"OC_RO\"}",
     "legendFormat": "Added"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"updated\",provider=\"OC_RO\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"skipped\",provider=\"OC_RO\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"deleted\",provider=\"OC_RO\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"error\",provider=\"OC_RO\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Watched Geokrety",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none", "label": "Users" }
   ],
   "targets": [
    { "expr": "geokrety_watched_total", "legendFormat": "Users watching" }
   ]
  },
  {
   "title": "OKAPI UK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"added\",provider=\"OC_UK\"}",
     "legendFormat": "Added"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"updated\",provider=\"OC_UK\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"skipped\",provider=\"OC_UK\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"deleted\",provider=\"OC_UK\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"error\",provider=\"OC_UK\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "OKAPI US",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"added\",provider=\"OC_US\"}",
     "legendFormat": "Added"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"updated\",provider=\"OC_US\"}",
     "legendFormat": "Updated"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"skipped\",provider=\"OC_US\"}",
     "legendFormat": "Skipped"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"deleted\",provider=\"OC_US\"}",
     "legendFormat": "Deleted"
    },
    {
     "expr": "geokrety_waypoint_okapi_sync{status=\"error\",provider=\"OC_US\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Moves Comments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Comments" }
   ],
   "targets": [
    { "expr": "geokrety_moves_comments_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Pages view",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(geokrety_total_requests[5m])",
     "legendFormat": "{{instance}}:{{verb}}"
    }
   ]
  },
  {
   "title": "Awards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "geokrety_award_awarded{award=\"created\"}",
     "legendFormat": "Awards"
    }
   ]
  },
  {
   "title": "News Comments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "Comments" }
   ],
   "targets": [
    { "expr": "geokrety_news_comments_total" }
   ]
  },
  {
   "title": "Pictures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geokrety_pictures_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Pictures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(geokrety_pictures_total)  ", "legendFormat": "Pictures Uploads" }
   ]
  },
  {
   "title": "Accounts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "none", "label": "Comments" }
   ],
   "targets": [
    { "expr": "geokrety_accounts_total" }
   ]
  }
 ]
}